function [folder_in_which_to_write,working_dwi_name,out_DT,out_KT,out_FA]=preproc_func_handle(folder_in_which_to_write,working_dwi_name,mask_name,numcores,do)
%This function is intended to do all preprocesing and give output names to
%the rest of the pipeline. Sadly, this will probably be by far the biggest
%contributor to the time it takes to run the whole pipeline.

%The mask generated here will probably be inferior to the mask generated by
%t1_preproc, because that mask was made with a better resolution/contrast
%image and because 5ttgen uses some nice BET options. In fact, you could take the
%5ttgen output and use that for probably an even better mask. In my
%experience, it's important to have a good mask for tractography, so I'd go
%with the t1 mask. The exception is the case in which there are bad EPI
%distortions and this function can't use topup to fix them -- in that case,
%the correspondence between the T1 anatomy and diffusion isn't assured.

%just grab these and write to the out folder (the use of d2n2s is justified
%here IMO bc it wraps 4 dir calls and 4 writes)
for i=1:numel(folder_in_which_to_write)

    %% move to 'dke' dir
    %grab image names for move
    dwis_noised=fullfile(folder_in_which_to_write{i},[working_dwi_name '.nii']);
    dwi_clean=d2n2s(folder_in_which_to_write{i}, make_flags('read','pick',dwis_noised,'no','bvalbvecjsonimg') ); %grab DWI related files to move but don't load them into matlab
    
    %after preproc, things should be going in the "final" folder with diffusion metrics and eventually tract outputs
    dwi_clean=move_obj_files(dwi_clean,fullfile(folder_in_which_to_write{i},'dke'),working_dwi_name); %assign again bc location of files has been updated
    
    %update the folder in which to write
    folder_in_which_to_write{i}=fullfile(folder_in_which_to_write{i},'dke');

%% get diffusion metrics
    % define in and out names
        
    out_DT=[folder_in_which_to_write{i} filesep 'DT.nii'];
    out_KT=[folder_in_which_to_write{i} filesep 'KT.nii'];
    out_FA=[folder_in_which_to_write{i} filesep 'fa.nii'];
    working_dwi_name='dwi_preprocd';

    system(['python designer.py \'...
        '-denoise -extent 5,5,5 \'...
        '-degibbs \'...
        '-rician \'...
        '-mask \'...
        '-prealign \'...
        '-smooth 1.25 \'...
        '-rpe_header -eddy \'...
        '-fit_constraints 0,1,0 \'...
        '-median \'...
        '-DKIparams -DTIparams \'...
        '-nthreads ' numcores ' '...
        dwi_clean(1).fns.nii ' '... %input nii -- if you need the json it's dwi_clean(1).fns.json
        folder_in_which_to_write{i} filesep working_dwi_name]) %output folder name (Think that's how it's supposed to go?)

end
end
